.PHONY: install uninstall reinstall plotsNR.pdf plotsVU.pdf

build: config obmaccs
	obuild build

config: consent.obuild
	obuild configure

clean:
	obuild clean
	\rm -f *.eps *.scores *.toplot *.CDF *.ccurve src/ob_maccs \
	       *.{002,003,005,010,020}.txt

edit:
	emacs src/*.ml TODO commands.sh &

obmaccs:
	cd src; make

install:
	opam remove consent
	opam pin -y add consent ${PWD}

uninstall:
	opam remove consent

reinstall: uninstall install

# unit tests
tests:
	qtest -o src/unit_tests.ml extract src/ROC.ml
	obuild build exe-unit_tests
	./unit_tests
	qtest -o src/unit_tests.ml extract src/myList.ml
	obuild build exe-unit_tests
	./unit_tests
	echo "(* DO NOT EDIT THIS FILE *)" > src/unit_tests.ml
