.PHONY: install uninstall reinstall

build: obmaccs
	jbuilder build @install

clean:
	jbuilder clean
	\rm -f *.eps *.scores *.toplot *.CDF *.ccurve src/ob_maccs \
	       *.{002,003,005,010,020}.txt

edit:
	emacs src/*.ml TODO commands.sh &

obmaccs:
	cd src; make

install:
	jbuilder build @install
	jbuilder install

uninstall:
	jbuilder uninstall

reinstall: uninstall install

# unit tests
tests:
	qtest -o src/unit_tests.ml extract src/ROC.ml
	jbuilder build src/unit_tests.exe
	_build/default/src/unit_tests.exe
	\rm -f _build/default/src/unit_tests.exe
	qtest -o src/unit_tests.ml extract src/myList.ml
	jbuilder build src/unit_tests.exe
	_build/default/src/unit_tests.exe	
	echo "(* DO NOT EDIT THIS FILE *)" > src/unit_tests.ml
